name: farmkarts
description: A new Flutter project.
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:

    sdk: ">=3.1.5 <3.3.4"


dependencies:
  flutter:
    sdk: flutter

  # Firebase core and authentication
  firebase_core: ^2.24.2
  firebase_auth: ^4.0.0
  firebase_database: ^10.4.0
  path_provider: ^2.0.15
  share_plus: ^7.2.1
  permission_handler: ^11.0.0

  # Additional Firebase services (uncomment as needed)
  # cloud_firestore: ^4.0.0
  # firebase_analytics: ^10.0.0

  http: 1.1.0
  intl: ^0.18.1
  shimmer: ^3.0.0
  printing: ^5.11.0
  # Other dependencies
  cupertino_icons: ^1.0.2
  dart_format: ^0.0.4
  pdf: ^3.10.0
  google_maps_flutter: ^2.5.0
  geolocation: ^10.1.0
  geocoding: ^2.1.0
  cloud_firestorm: ^4.9.1
  flutter_spin kit: ^5.2.0
  flutter_local_notifications: ^16.3.1
  google_fonts: ^6.1.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Override dependencies to resolve potential conflicts
dependency_overrides:
  collection: ^1.16.0

flutter:
  uses-material-design: true
