name: farmkarts
description: A new Flutter project.
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:

    sdk: ">=3.1.5 <3.3.4"


dependencies:
  flutter:
    sdk: flutter

  # Firebase core and authentication
  firebase_core: ^2.24.2
  firebase_auth: ^4.0.0
  firebase_database: ^10.4.0
  # Additional Firebase services (uncomment as needed)
  # cloud_firestore: ^4.0.0
  # firebase_analytics: ^10.0.0
  http: 1.1.0

  # Other dependencies
  cupertino_icons: ^1.0.2
  dart_format: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Override dependencies to resolve potential conflicts
dependency_overrides:
  collection: ^1.16.0

flutter:
  uses-material-design: true
