// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBirSzwlaVmycUCxpAE4324nxibd4THy4o',
    appId: '1:709785957438:web:79a3c3de4243c0ed134d6f',
    messagingSenderId: '709785957438',
    projectId: 'farmkart-9f4f3',
    authDomain: 'farmkart-9f4f3.firebaseapp.com',
    databaseURL: 'https://farmkart-9f4f3-default-rtdb.firebaseio.com',
    storageBucket: 'farmkart-9f4f3.firebasestorage.app',
    measurementId: 'G-EZMC38TXE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYGPfM-kQ5jIZzRNN059ASTo2Wiy-CHd8',
    appId: '1:709785957438:android:2f747a5a153a33b0134d6f',
    messagingSenderId: '709785957438',
    projectId: 'farmkart-9f4f3',
    databaseURL: 'https://farmkart-9f4f3-default-rtdb.firebaseio.com',
    storageBucket: 'farmkart-9f4f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOozNkyFeSAvXFyeWgLChgjvzTQXecv5s',
    appId: '1:709785957438:ios:47337aadcc9007e7134d6f',
    messagingSenderId: '709785957438',
    projectId: 'farmkart-9f4f3',
    databaseURL: 'https://farmkart-9f4f3-default-rtdb.firebaseio.com',
    storageBucket: 'farmkart-9f4f3.firebasestorage.app',
    iosBundleId: 'com.example.farmkarts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOozNkyFeSAvXFyeWgLChgjvzTQXecv5s',
    appId: '1:709785957438:ios:47337aadcc9007e7134d6f',
    messagingSenderId: '709785957438',
    projectId: 'farmkart-9f4f3',
    databaseURL: 'https://farmkart-9f4f3-default-rtdb.firebaseio.com',
    storageBucket: 'farmkart-9f4f3.firebasestorage.app',
    iosBundleId: 'com.example.farmkarts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBirSzwlaVmycUCxpAE4324nxibd4THy4o',
    appId: '1:709785957438:web:690b4897273ffffa134d6f',
    messagingSenderId: '709785957438',
    projectId: 'farmkart-9f4f3',
    authDomain: 'farmkart-9f4f3.firebaseapp.com',
    databaseURL: 'https://farmkart-9f4f3-default-rtdb.firebaseio.com',
    storageBucket: 'farmkart-9f4f3.firebasestorage.app',
    measurementId: 'G-RFF4TNMLJ2',
  );
}
